apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dutchdelhicacy
  name: ruudniewtv-stream-website-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
